// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <dplyr.h>
#include <Rcpp.h>

using namespace Rcpp;

// map_impl
SEXP map_impl(Environment env, std::string x_name, std::string f_name);
RcppExport SEXP purrr_map_impl(SEXP envSEXP, SEXP x_nameSEXP, SEXP f_nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Environment >::type env(envSEXP);
    Rcpp::traits::input_parameter< std::string >::type x_name(x_nameSEXP);
    Rcpp::traits::input_parameter< std::string >::type f_name(f_nameSEXP);
    __result = Rcpp::wrap(map_impl(env, x_name, f_name));
    return __result;
END_RCPP
}
// process_slices
SEXP process_slices(List& results, const List& slicers, const List& labels, int include_labels, int row_id);
RcppExport SEXP purrr_process_slices(SEXP resultsSEXP, SEXP slicersSEXP, SEXP labelsSEXP, SEXP include_labelsSEXP, SEXP row_idSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List& >::type results(resultsSEXP);
    Rcpp::traits::input_parameter< const List& >::type slicers(slicersSEXP);
    Rcpp::traits::input_parameter< const List& >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< int >::type include_labels(include_labelsSEXP);
    Rcpp::traits::input_parameter< int >::type row_id(row_idSEXP);
    __result = Rcpp::wrap(process_slices(results, slicers, labels, include_labels, row_id));
    return __result;
END_RCPP
}
// by_slice_impl
SEXP by_slice_impl(const List& data, const SEXP fun, SEXP dots, int include_labels, const Environment& calling_env);
RcppExport SEXP purrr_by_slice_impl(SEXP dataSEXP, SEXP funSEXP, SEXP dotsSEXP, SEXP include_labelsSEXP, SEXP calling_envSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const List& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const SEXP >::type fun(funSEXP);
    Rcpp::traits::input_parameter< SEXP >::type dots(dotsSEXP);
    Rcpp::traits::input_parameter< int >::type include_labels(include_labelsSEXP);
    Rcpp::traits::input_parameter< const Environment& >::type calling_env(calling_envSEXP);
    __result = Rcpp::wrap(by_slice_impl(data, fun, dots, include_labels, calling_env));
    return __result;
END_RCPP
}
// by_row_impl
SEXP by_row_impl(const List& data, const SEXP fun, SEXP dots, int include_labels, const Environment& calling_env);
RcppExport SEXP purrr_by_row_impl(SEXP dataSEXP, SEXP funSEXP, SEXP dotsSEXP, SEXP include_labelsSEXP, SEXP calling_envSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const List& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const SEXP >::type fun(funSEXP);
    Rcpp::traits::input_parameter< SEXP >::type dots(dotsSEXP);
    Rcpp::traits::input_parameter< int >::type include_labels(include_labelsSEXP);
    Rcpp::traits::input_parameter< const Environment& >::type calling_env(calling_envSEXP);
    __result = Rcpp::wrap(by_row_impl(data, fun, dots, include_labels, calling_env));
    return __result;
END_RCPP
}
