#' Best practices for exporting adverb-wrapped functions
#'
#' @description
#'
#' Functions like [insistently()], [safely()], [slowly()], and [quietly()] help
#' resolve challenging issues in programming. For example, [safely()] modifies a
#' function to return both an error and a result. These functions work by
#' returning an enhanced version of the original function. They are often called
#' 'adverb' functions, typically named something like `insist_scrape_data` or
#' `safe_scrape_data`.
#'
#' Distributing an adverb function like `safe_scrape_data` in an R package
#' requires using a special function called `.onLoad()`. This is because these
#' functions are generated by `purrr` code, and assigning functions in your
#' namespace at build time might cause issues. For example, when `purrr` is
#' updated, and your package is not. This would mean the functions you create in
#' the package will contain the old source code, and may even refer to functions
#' that no longer exist in the `purrr` namespace.
#'
#' An example if provided below for `insist`, but it would be very similar for
#' these other "adverb" type functions.

#' ```
#' #' My function
#  '#' @export
#' insist_my_function <- function(...) "dummy"
#'
#' my_function <- function(...) {
#'   # Implementation
#' }
#'
#' .onLoad <- function(lib, pkg) {
#'   insist_my_function <<- purrr::insistently(my_function)
#' }
#'```
#'
#' @name exporting-adverbs
NULL
