# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

process_slices <- function(results, slicers, labels, include_labels, output_colname, row_id = 0L) {
    .Call('purrr_process_slices', PACKAGE = 'purrr', results, slicers, labels, include_labels, output_colname, row_id)
}

by_slice_impl <- function(data, fun, dots, include_labels, calling_env, output_colname) {
    .Call('purrr_by_slice_impl', PACKAGE = 'purrr', data, fun, dots, include_labels, calling_env, output_colname)
}

by_row_impl <- function(data, fun, dots, include_labels, calling_env, output_colname) {
    .Call('purrr_by_row_impl', PACKAGE = 'purrr', data, fun, dots, include_labels, calling_env, output_colname)
}

